name: Qmake CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Qt
      uses: jurplel/install-qt-action@v3.3.0
      with:
        source: false
        documentation: false
        examples: false
    - name: Create build dir
      run: pwd && mkdir -p build
    - name: qmake
      run: cd build && qmake ../IDE.pro
    - name: make
      run: cd build && make
